<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnCookies</name>
   <tag></tag>
   <elementGuidId>ce07e6bc-d5d5-4798-9efe-5f951cd0f427</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id='CybotCookiebotDialogBodyLevelButtonAccept']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id='CybotCookiebotDialogBodyLevelButtonAccept']</value>
   </webElementProperties>
</WebElementEntity>
