<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>imgSetTimeZone</name>
   <tag></tag>
   <elementGuidId>bdf33304-9475-4c97-a1b8-7c3e20388ea6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@class=&quot;v-button-wrap&quot;]/img[contains(@src,'timezone.png')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class=&quot;v-button-wrap&quot;]/img[contains(@src,'timezone.png')]</value>
   </webElementProperties>
</WebElementEntity>
