<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>imgSetLocation</name>
   <tag></tag>
   <elementGuidId>a9552114-8eac-415d-ace7-f6caea5e0f6b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@class=&quot;v-button-wrap&quot;]/img[contains(@src,'images/location_marker.png')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class=&quot;v-button-wrap&quot;]/img[contains(@src,'images/location_marker.png')]</value>
   </webElementProperties>
</WebElementEntity>
