<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtEventStartDate</name>
   <tag></tag>
   <elementGuidId>65d5c4e0-aaf9-4dcf-a1f6-b75379310f67</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@id='EventStartDate/Time:']/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@id='EventStartDate/Time:']/input</value>
   </webElementProperties>
</WebElementEntity>
